edit in yml file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -21,6 +21,6 @@ jobs:
               cd CI_CD_Pipeline_Setup-Project
               git pull origin master || (echo "Failed to pull existing repository" && exit 1)
             else
-              git clone https://github.com/Mohdniyam/CI_CD_Pipeline_Setup-Project.git || (echo "Failed to clone repository" && exit 1)
+              git clone https://github.com/Mohdniyam/cicd_backend.git || (echo "Failed to clone repository" && exit 1)
             fi
             echo 'Deployment successful to DigitalOcean'
